name: example
description: An example to keyed_collection_widgets package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  enum_map: ^0.1.0
  flutter: { sdk: flutter }
  keyed_collection_widgets: { path: ../ }

dev_dependencies:
  build_runner: ^2.2.0
  enum_map_gen: ^0.1.0
  flutter_test: { sdk: flutter }
  total_lints: ^2.18.0

flutter:
  uses-material-design: true
