name: keyed_collection_widgets
description: BottomNavigationBar, IndexedStack, and TabController that use item keys instead of indexes.
version: 0.3.3
homepage: https://github.com/alexeyinkin/flutter-keyed-collection-widgets

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  total_lints: ^2.17.0
