name: keyed_collection_widgets
description: BottomNavigationBar, IndexedStack, and TabController that use item keys instead of indexes.
version: 0.4.4
homepage: https://github.com/alexeyinkin/flutter-keyed-collection-widgets

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.16.0
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }
  golden_toolkit: ^0.15.0
  total_lints: ^3.4.0
