name: keyed_collection_widgets
description: BottomNavigationBar, IndexedStack and TabController that use item keys instead of indexes.
version: 0.2.0
homepage: https://github.com/alexeyinkin/flutter-keyed-collection-widgets

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
